# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField(default=False)),
                ('tagged', models.BooleanField(default=False)),
                ('text', models.TextField(blank=True, help_text=None, null=True)),
                ('image', models.ImageField(blank=True, height_field=b'image_height', null=True, upload_to=b'upload/images/%s.%N', width_field=b'image_width')),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('preview', models.ImageField(blank=True, null=True, upload_to=b'images/%s')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=b'images/%s')),
                ('action', models.CharField(blank=True, choices=[(b'like', b'like'), (b'follow', 'doda\u0142/a ci\u0119 do obserwowanych'), (b'unfollow', 'przesta\u0142/a ci\u0119 obserwowa\u0107'), (b'mention', 'm\xf3wi o tobie'), (b'quote', 'cytuje ci\u0119'), (b'watch', b'subskrybuje tag'), (b'unwatch', b'ju\xc5\xbc nie subskrybuje tagu')], max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('status', models.ManyToManyField(to='cockpit.Status')),
            ],
        ),
    ]
